const API_URL=''; // Apps Script /exec URL goes here when ready.
const demo={colleagues:[{id:'1001',name:'Des',contract:39,skills:['Cook','Open','Till']},{id:'1002',name:'Christina',contract:20,skills:['Till','Plate up']},{id:'1003',name:'Richard',contract:20,skills:['Cook','Close']},{id:'1004',name:'Judith',contract:8,skills:['Till','Plate up']}],absences:[{id:'ABS-0001',till:'1003',type:'Sickness',start:'2026-10-05',end:'',notes:'Ongoing'}],regular:[{till:'1004',day:'Saturday',shift:'Till / Plate Up',start:'08:00',end:'16:00'}],shifts:[{name:'Morning Cook',start:'07:00',end:'14:00',skill:'Cook'},{name:'Till / Plate Up',start:'08:00',end:'14:00',skill:'Till'},{name:'Lunch Cover',start:'11:00',end:'14:00',skill:'Till'},{name:'Close Down',start:'14:00',end:'18:00',skill:'Close'}]};
let data=structuredClone(demo),assignments={};const days=['Monday','Tuesday','Wednesday','Thursday','Friday','Saturday','Sunday'];
const $=s=>document.querySelector(s);function show(id){document.querySelectorAll('.screen').forEach(x=>x.classList.remove('active'));$('#'+id).classList.add('active');if(id==='rota')renderRota();if(id==='absences')renderAbsences();if(id==='regular')renderRegular();if(id==='colleagues')renderColleagues()}
document.querySelectorAll('[data-screen]').forEach(b=>b.onclick=()=>show(b.dataset.screen));$('#homeBtn').onclick=()=>show('dashboard');
function monday(){let d=new Date();d.setDate(d.getDate()-((d.getDay()+6)%7));return d.toISOString().slice(0,10)}$('#week').value=monday();$('#week').onchange=renderRota;
function person(id){return data.colleagues.find(c=>c.id===id)}function absent(id,date){return data.absences.some(a=>a.till===id&&a.start<=date&&(!a.end||a.end>=date))}function dateFor(day){let d=new Date($('#week').value+'T12:00:00');d.setDate(d.getDate()+days.indexOf(day));return d.toISOString().slice(0,10)}
function regularFor(day,shift){return data.regular.find(r=>r.day===day&&r.shift===shift)}function eligible(day,s){let date=dateFor(day);return data.colleagues.filter(c=>c.skills.includes(s.skill)&&!absent(c.id,date))}
function hours(id){let total=0;Object.values(assignments).forEach(a=>{if(a.id===id)total+=a.hours});return total}function duration(a,b){let [ah,am]=a.split(':').map(Number),[bh,bm]=b.split(':').map(Number);return (bh*60+bm-ah*60-am)/60}
function renderRota(){let html='';days.forEach(day=>{html+=`<div class="day"><h3>${day}</h3>`;data.shifts.forEach((s,i)=>{let key=day+'-'+i,reg=regularFor(day,s.name),regPerson=reg&&person(reg.till),isAway=regPerson&&absent(reg.till,dateFor(day));let selected=assignments[key]?.id||(!isAway&&regPerson?.id)||'';if(selected&&!assignments[key])assignments[key]={id:selected,hours:duration(s.start,s.end),status:'regular'};let status=isAway?'cover':selected?(assignments[key]?.status==='regular'?'regular':'manual'):'unfilled';let label=isAway?`COVER REQUIRED — ${regPerson.name} absent`:status==='regular'?'REGULAR':status==='manual'?'MANUAL':'UNFILLED';let opts='<option value="">Select suitable colleague</option>'+eligible(day,s).map(c=>`<option value="${c.id}" ${selected===c.id?'selected':''}>${c.name} — ${hours(c.id)}/${c.contract} hrs</option>`).join('');html+=`<div class="shift"><div class="shiftTitle"><b>${s.name}</b><span class="small">${s.start}–${s.end} · ${duration(s.start,s.end)} hrs</span><br><span class="badge ${status}">${label}</span></div><div class="small">Core coverage: ${s.end>'11:00'&&s.start<'14:00'?'11:00–14:00 ✓':'support shift'}</div><select data-key="${key}" data-hours="${duration(s.start,s.end)}">${opts}</select></div>`});html+='</div>'});$('#days').innerHTML=html;document.querySelectorAll('.shift select').forEach(x=>x.onchange=()=>{if(x.value)assignments[x.dataset.key]={id:x.value,hours:+x.dataset.hours,status:'manual'};else delete assignments[x.dataset.key];renderRota()});renderSummary()}
function renderSummary(){let filled=Object.keys(assignments).length,total=days.length*data.shifts.length,weekend=new Set();Object.entries(assignments).forEach(([k,a])=>{if(/Friday|Saturday|Sunday/.test(k))weekend.add(a.id)});$('#rotaSummary').innerHTML=`<div class="stat"><b>${filled}/${total}</b>shifts filled</div><div class="stat"><b>${data.colleagues.filter(c=>hours(c.id)>=c.contract).length}/${data.colleagues.length}</b>contracts reached</div><div class="stat"><b>${weekend.size}/${data.colleagues.length}</b>weekend rule met</div>`}
function renderAbsences(){let sel=data.colleagues.map(c=>`<option value="${c.id}">${c.name} · Till ${c.id}</option>`).join('');$('#absencePerson').innerHTML=sel;$('#absenceList').innerHTML=data.absences.map(a=>{let c=person(a.till);return `<div class="person"><div><b>${c?.name||a.till}</b><div class="small">${a.type}: ${a.start} → ${a.end||'ongoing'}</div></div><span class="badge cover">${a.end?'ACTIVE':'ONGOING'}</span></div>`}).join('')||'<p>No absences recorded.</p>'}
$('#absenceType').onchange=()=>$('#ongoingWrap').style.display=$('#absenceType').value==='Sickness'?'flex':'none';$('#absenceForm').onsubmit=e=>{e.preventDefault();let ongoing=$('#ongoing').checked&&$('#absenceType').value==='Sickness';data.absences.push({id:'ABS-'+Date.now(),till:$('#absencePerson').value,type:$('#absenceType').value,start:$('#absenceStart').value,end:ongoing?'':$('#absenceEnd').value,notes:$('#absenceNotes').value});e.target.reset();renderAbsences();toast('Absence saved — affected regular shifts will require cover.')};
function renderRegular(){$('#regularList').innerHTML=data.regular.map(r=>`<div class="person"><div><b>${person(r.till)?.name}</b><div class="small">${r.day} · ${r.shift}</div></div><b>${r.start}–${r.end}</b></div>`).join('')}
function renderColleagues(){$('#colleagueList').innerHTML=data.colleagues.map(c=>`<div class="person"><div><b>${c.name}</b><div class="small">Till ${c.id} · ${c.skills.join(', ')}</div></div><span class="hours">${hours(c.id)} / ${c.contract} hrs</span></div>`).join('')}
function toast(t){$('#toast').textContent=t;$('#toast').style.display='block';setTimeout(()=>$('#toast').style.display='none',2500)}
$('#absenceType').dispatchEvent(new Event('change'));