const APP_VERSION='2026.10.06-live-02';
const API_URL='https://script.google.com/macros/s/AKfycbzyPL_LOIgzOCBM0U4Lr1HCQsqCPZ_xg47Ry2bn7-AHiKWWRiwiAPIsM-hClqUSszje-g/exec';
const DATA_URL=API_URL+'?action=bootstrap';
const days=['Monday','Tuesday','Wednesday','Thursday','Friday','Saturday','Sunday'];
let data=null,assignments={},currentDataVersion='';
const $=s=>document.querySelector(s);
function show(id){document.querySelectorAll('.screen').forEach(x=>x.classList.remove('active'));$('#'+id).classList.add('active');if(id==='rota')renderRota();if(id==='absences')renderAbsences();if(id==='regular')renderRegular();if(id==='colleagues')renderColleagues()}
document.querySelectorAll('[data-screen]').forEach(b=>b.onclick=()=>show(b.dataset.screen));$('#homeBtn').onclick=()=>show('dashboard');
function monday(){let d=new Date();d.setDate(d.getDate()-((d.getDay()+6)%7));return d.toISOString().slice(0,10)}$('#week').value=monday();$('#week').onchange=renderRota;
function mins(t){let [h,m]=String(t).split(':').map(Number);return h*60+m}function elapsed(a,b){return (mins(b)-mins(a))/60}function paid(a,b){let e=elapsed(a,b);return e-(e>6?.25:0)}function breakMins(a,b){return elapsed(a,b)>6?15:0}
function person(id){return data.colleagues.find(c=>c.id===id)}function dateFor(day){let d=new Date($('#week').value+'T12:00:00');d.setDate(d.getDate()+days.indexOf(day));return d.toISOString().slice(0,10)}
function absent(id,date){return (data.absences||[]).some(a=>a.till===id&&a.start<=date&&(!a.end||a.end>=date))}
function available(c,day,s){let a=data.availability?.[c.id]?.[day];if(!a)return false;let f=String(a.from||'').toLowerCase(),u=String(a.until||'').toLowerCase();if(['off','sick',''].includes(f)||['off','sick',''].includes(u))return false;return mins(a.from)<=mins(s.start)&&mins(a.until)>=mins(s.end)}
function skilled(c,s){return (s.skillsAny||[]).some(x=>c.skills.includes(x))}function eligible(day,s){return data.colleagues.filter(c=>available(c,day,s)&&skilled(c,s)&&!absent(c.id,dateFor(day)))}
function hours(id){return Object.values(assignments).filter(a=>a.id===id).reduce((n,a)=>n+a.paid,0)}
function validate(d){if(!d||!Array.isArray(d.colleagues)||!d.colleagues.length)throw Error('No colleagues returned.');if(!d.availability||!Array.isArray(d.shifts)||!d.shifts.length)throw Error('Staffing data is incomplete.');let sup=d.colleagues.find(c=>c.id==='344');if(!sup||!sup.supervisor)throw Error('Supervisor check failed: till 344 must be Christina.')}
async function loadStaffingData(manual=false){setDataStatus('loading','Loading latest staffing data…');try{let r=await fetch(`${DATA_URL}&_=${Date.now()}`,{cache:'no-store',headers:{Accept:'application/json'}});if(!r.ok)throw Error(`HTTP ${r.status}`);let fresh=await r.json();validate(fresh);let changed=currentDataVersion&&currentDataVersion!==fresh.meta?.version;data=fresh;currentDataVersion=fresh.meta?.version||'unversioned';assignments={};updateDataPanel();setDataStatus('live',`LIVE · ${data.colleagues.length} colleagues`);if(manual)toast(changed?'New staffing data loaded.':'Data reloaded — no version change found.');if($('#rota').classList.contains('active'))renderRota();if($('#colleagues').classList.contains('active'))renderColleagues();return true}catch(e){data=null;assignments={};setDataStatus('error','CURRENT DATA NOT LOADED');$('#dataDetail').textContent=`Load failed: ${e.message}. Old cached staffing data has NOT been used.`;toast('Could not load current staffing data.');return false}}
function setDataStatus(kind,text){let el=$('#dataStatus');el.className='dataStatus '+kind;el.textContent=text}
function updateDataPanel(){let m=data.meta||{},c=person('344');$('#dataDetail').textContent=`App ${APP_VERSION} · Data ${m.version||'?'} · ${m.dataset||m.source||'staffing source'} · fetched ${new Date().toLocaleTimeString('en-GB')} · Christina ${c?'Till '+c.id+' · Supervisor':'CHECK FAILED'}`}
$('#reloadData').onclick=()=>loadStaffingData(true);
function renderRota(){if(!data){$('#days').innerHTML='<div class="errorCard">Current staffing data is not loaded. Use Reload Staffing Data.</div>';return}let html='';days.forEach(day=>{let shifts=data.shifts.filter(s=>s.day===day);html+=`<div class="day"><h3>${day}</h3>`;shifts.forEach((s,i)=>{let key=day+'-'+i,selected=assignments[key]?.id||'',list=eligible(day,s);let opts='<option value="">Select suitable colleague</option>'+list.map(c=>`<option value="${c.id}" ${selected===c.id?'selected':''}>${c.name}${c.supervisor?' · Supervisor':''} — ${hours(c.id).toFixed(2)}/${c.contract} hrs</option>`).join('');let e=elapsed(s.start,s.end),p=paid(s.start,s.end),br=breakMins(s.start,s.end),cost=p*(data.meta?.testHourlyRate||0);html+=`<div class="shift"><div class="shiftTitle"><b>${s.name}</b><span class="small">${s.start}–${s.end} · ${e.toFixed(2)} elapsed · ${br}m break · ${p.toFixed(2)} paid</span><br><span class="badge ${selected?'manual':'unfilled'}">${selected?'ASSIGNED':'UNFILLED'}</span></div><div class="small">Needs: ${(s.skillsAny||[]).join(' / ')}<br>Test cost: £${cost.toFixed(2)}</div><select data-key="${key}" data-day="${day}" data-name="${s.name}">${opts}</select></div>`});html+='</div>'});$('#days').innerHTML=html;document.querySelectorAll('.shift select').forEach(x=>x.onchange=()=>{let s=data.shifts.find(z=>z.day===x.dataset.day&&z.name===x.dataset.name);if(x.value)assignments[x.dataset.key]={id:x.value,elapsed:elapsed(s.start,s.end),breakMinutes:breakMins(s.start,s.end),paid:paid(s.start,s.end),budgetCost:paid(s.start,s.end)*(data.meta?.testHourlyRate||0)};else delete assignments[x.dataset.key];renderRota()});renderSummary()}
function renderSummary(){let filled=Object.keys(assignments).length,total=data.shifts.length,weekend=new Set(),cost=0;Object.entries(assignments).forEach(([k,a])=>{if(/Friday|Saturday|Sunday/.test(k))weekend.add(a.id);cost+=a.budgetCost||0});$('#rotaSummary').innerHTML=`<div class="stat"><b>${filled}/${total}</b>shifts filled</div><div class="stat"><b>${data.colleagues.filter(c=>hours(c.id)>=c.contract).length}/${data.colleagues.length}</b>contracts reached</div><div class="stat"><b>${weekend.size}</b>worked Fri/Sat/Sun</div><div class="stat"><b>£${cost.toFixed(2)}</b>test budget cost</div>`}
function renderAbsences(){if(!data)return;$('#absencePerson').innerHTML=data.colleagues.map(c=>`<option value="${c.id}">${c.name} · Till ${c.id}</option>`).join('');$('#absenceList').innerHTML=(data.absences||[]).map(a=>`<div class="person"><div><b>${person(a.till)?.name||a.till}</b><div class="small">${a.type}: ${a.start} → ${a.end||'ongoing'}</div></div></div>`).join('')||'<p>No test absences recorded.</p>'}
$('#absenceType').onchange=()=>$('#ongoingWrap').style.display=$('#absenceType').value==='Sickness'?'flex':'none';$('#absenceForm').onsubmit=e=>{e.preventDefault();if(!data)return;let ongoing=$('#ongoing').checked&&$('#absenceType').value==='Sickness';data.absences.push({id:'TEST-'+Date.now(),till:$('#absencePerson').value,type:$('#absenceType').value,start:$('#absenceStart').value,end:ongoing?'':$('#absenceEnd').value,notes:$('#absenceNotes').value});e.target.reset();renderAbsences();toast('Test absence added for this browser session.')};
function renderRegular(){if(!data)return;$('#regularList').innerHTML='<p>No regular shifts imported in this test fixture yet.</p>'}
function renderColleagues(){if(!data)return;$('#colleagueList').innerHTML=data.colleagues.map(c=>{let a=data.availability?.[c.id]||{};let av=days.map(d=>`${d.slice(0,3)} ${a[d]?.from||'?'}–${a[d]?.until||'?'}`).join(' · ');return `<div class="person"><div><b>${c.name}${c.supervisor?' · Supervisor':''}</b><div class="small">Till ${c.id} · ${c.skills.join(', ')}</div><div class="small">${av}</div></div><span class="hours">${hours(c.id).toFixed(2)} / ${c.contract} hrs</span></div>`}).join('')}
function toast(t){$('#toast').textContent=t;$('#toast').style.display='block';setTimeout(()=>$('#toast').style.display='none',2800)}
$('#absenceType').dispatchEvent(new Event('change'));loadStaffingData();
function setDataStatus(kind,text){let e=$('#dataStatus');if(e){e.className='dataStatus '+kind;e.textContent=text}}
function updateDataPanel(){let c=data.colleagues.find(x=>x.id==='344'),m=data.meta||{};$('#dataDetail').textContent='App '+APP_VERSION+' · Data '+(m.version||'?')+' · '+(m.dataset||m.source||'source')+' · fetched '+new Date().toLocaleTimeString('en-GB')+' · Christina '+(c&&c.supervisor?'Till 344 · Supervisor':'CHECK FAILED')}
async function loadStaffingData(manual=false){setDataStatus('loading','Loading latest staffing data…');try{let r=await fetch(DATA_URL+'&_='+Date.now(),{cache:'no-store',headers:{Accept:'application/json'}});if(!r.ok)throw Error('HTTP '+r.status);let fresh=await r.json();if(!fresh.colleagues?.length||!fresh.shifts?.length)throw Error('Incomplete staffing data');let sup=fresh.colleagues.find(c=>c.id==='344');if(!sup||!sup.supervisor)throw Error('Supervisor check failed');let changed=currentDataVersion&&currentDataVersion!==fresh.meta?.version;data=fresh;currentDataVersion=fresh.meta?.version||'unversioned';assignments={};updateDataPanel();setDataStatus('live','LIVE · '+data.colleagues.length+' colleagues');if(manual)toast(changed?'New staffing data loaded.':'Data reloaded — no version change found.');if($('#rota').classList.contains('active'))renderRota();if($('#colleagues').classList.contains('active'))renderColleagues()}catch(e){data={colleagues:[],availability:{},absences:[],regular:[],shifts:[],meta:{}};assignments={};setDataStatus('error','CURRENT DATA NOT LOADED');$('#dataDetail').textContent='Load failed: '+e.message+'. Old cached staffing data has NOT been used.'}}
$('#reloadData').onclick=()=>loadStaffingData(true);loadStaffingData();
